In [22]:
import json
import pandas as pd
from matplotlib import pyplot as plt

#### Let's explore tags content for a sample of changesets

In [66]:
# First we run the fetch_and_process_changesets function locally
range_inf,range_sup = 6135330, 6135350
!python manage.py shell -c \
    "from changesets.osm_fetcher import fetch_and_process_changesets; fetch_and_process_changesets({range_inf},{range_sup}, save_locally=True)"

/Users/hadi/Documents/coding/side_projects/osm_projects/osm_django_api/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Sequence 6135330 already processed.
Sequence 6135331 already processed.
Sequence 6135332 already processed.
Sequence 6135333 already processed.
Sequence 6135334 already processed.
Sequence 6135335 already processed.
Sequence 6135336 already processed.
Sequence 6135337 already processed.
Sequence 6135338 already processed.
Sequence 6135339 already processed.
Sequence 6135340 already processed.
Sequence 6135341 already processed.
Sequence 6135342 already processed.
Sequence 6135343 already processed.
Sequence 6135344 already processed.
Sequence 6135345 already processed.
Sequence 6135346 already processed.
Sequence 6135347 already processed.
Sequence 6135348 already processed.
Sequence 6135349 already processed.
Sequence 6135350 already processed.

#### We read the local data and save it in "all_data" variable

In [67]:
all_data = []
changesets = range(range_inf, range_sup)
# import .jsonl files from output directory
for i in changesets:
    with open(f'output/{i}.jsonl', 'r') as f:
        data = [json.loads(line) for line in f]
        all_data.extend(data)

In [68]:
len(all_data)

1054

### Number of unique tag keys:

In [69]:
def get_unique_tag_keys(data):
    set_ = set()
    for d in data:
        set_ = set_.union(set(d['tags'].keys()))
    return set_

print(len(get_unique_tag_keys(all_data)))
print(get_unique_tag_keys(all_data))

56
{'info:features_merged', 'resolved:close_nodes:vertices', 'warnings:almost_junction:highway-highway', 'host', 'warnings:mismatched_geometry:point_as_line', 'create', 'ideditor:walkthrough_started', 'fixing_osm_roads', 'locale', 'data_used', 'theme', 'warnings:suspicious_name:generic_name', 'ideditor:walkthrough_progress', 'closed:note', 'warnings:crossing_ways:building-highway', 'resolved:mismatched_geometry:line_as_vertex', 'warnings:outdated_tags:noncanonical_brand', 'warnings:crossing_ways:highway-waterway', 'resolved:crossing_ways:building-highway', 'bundle_id', 'resolved:outdated_tags:noncanonical_brand', 'hashtags', 'cases_where_human_help_is_required', 'warnings:disconnected_way:highway', 'resolved:crossing_ways:highway-highway', 'created_by', 'discussion_before_edits', 'bot', 'resolved:crossing_ways:highway-waterway', 'resolved:outdated_tags:deprecated_tags', 'ideditor:walkthrough_completed', 'imagery_used', 'resolved:mismatched_geometry:point_as_vertex', 'created_by:library', 'source', 'review_requested', 'changesets_count', 'created_by_library', 'warnings:missing_tag:descriptive', 'resolved:help_request:fixme_tag', 'StreetComplete:quest_type', 'resolved:crossing_ways:highway-railway', 'website', 'warnings:close_nodes:vertices', 'comment', 'answer', 'resolved:crossing_ways:building-building', 'resolved:outdated_tags:incomplete_tags', 'description', 'resolved:disconnected_way:highway', 'resolved:almost_junction:highway-highway', 'warnings:crossing_ways:building-building', 'osm_wiki_documentation_page', 'mechanical', 'resolved:mismatched_geometry:vertex_as_point', 'warnings:crossing_ways:highway-highway'}

### Let's sum up all the unique tags in a DataFrame

In [70]:
all_tags = []
for data in all_data:
    all_tags.append(data['tags'])

df_tags = pd.DataFrame(all_tags)

df_tags.head(3)

,comment,created_by,locale,source,StreetComplete:quest_type,changesets_count,host,ideditor:walkthrough_completed,ideditor:walkthrough_progress,ideditor:walkthrough_started,...,warnings:crossing_ways:building-building,resolved:crossing_ways:building-highway,resolved:crossing_ways:highway-railway,created_by:library,website,answer,warnings:close_nodes:vertices,resolved:crossing_ways:highway-highway,warnings:outdated_tags:noncanonical_brand,resolved:crossing_ways:building-building
0,Specify parking types,StreetComplete 58.2,de-DE,survey,AddParkingType,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Specify whether public transport stops have bins,StreetComplete 58.2,de-DE,survey,AddBinStatusOnBusStop,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Specify whether pedestrian crossings have islands,StreetComplete 58.2,de-DE,survey,AddCrossingIsland,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Number of unique values per tag ?
#### (less unique values makes the tag a good candidate for becoming a Changeset model attribute)

In [71]:
df_uniques = pd.DataFrame(df_tags.nunique()).reset_index().rename(columns={'index': 'tag', 0: 'unique_values'})
df_uniques

                                             tag  unique_values
0                                        comment            543
1                                     created_by             73
2                                         locale             47
3                                         source             99
4                      StreetComplete:quest_type            111
5                               changesets_count            322
6                                           host             13
7                 ideditor:walkthrough_completed              1
8                  ideditor:walkthrough_progress              8
9                   ideditor:walkthrough_started              1
10                                  imagery_used             73
11                                      hashtags             37
12      resolved:almost_junction:highway-highway              1
13                                     data_used              2
14               resolved:help_request:fixme_tag              1
15  resolved:mismatched_geometry:point_as_vertex              1
16        resolved:outdated_tags:incomplete_tags              4
17     resolved:outdated_tags:noncanonical_brand              4
18                 resolved:close_nodes:vertices              1
19       warnings:crossing_ways:highway-waterway              2
20              warnings:missing_tag:descriptive              1
21                                     bundle_id              1
22       warnings:crossing_ways:building-highway              1
23             warnings:disconnected_way:highway              3
24                                   closed:note              1
25      warnings:almost_junction:highway-highway              1
26                              fixing_osm_roads              1
27                                           bot              1
28            cases_where_human_help_is_required              1
29                            created_by_library              1
30                       discussion_before_edits              1
31                                    mechanical              1
32                   osm_wiki_documentation_page              1
33                              review_requested              1
34                                   description              1
35                                        create              1
36                                         theme              2
37       resolved:crossing_ways:highway-waterway              2
38        resolved:outdated_tags:deprecated_tags              1
39                          info:features_merged              1
40         warnings:suspicious_name:generic_name              1
41   resolved:mismatched_geometry:line_as_vertex              1
42  resolved:mismatched_geometry:vertex_as_point              2
43        warnings:crossing_ways:highway-highway              2
44             resolved:disconnected_way:highway              1
45    warnings:mismatched_geometry:point_as_line              1
46      warnings:crossing_ways:building-building              1
47       resolved:crossing_ways:building-highway              3
48        resolved:crossing_ways:highway-railway              1
49                            created_by:library              1
50                                       website              1
51                                        answer              1
52                 warnings:close_nodes:vertices              1
53        resolved:crossing_ways:highway-highway              1
54     warnings:outdated_tags:noncanonical_brand              1
55      resolved:crossing_ways:building-building              1

In [89]:
df_tags['hashtags'].unique()

array([nan, '#hotosm-project-16817;#UNMappers;#UNMOGIP;#Jammu;#Kashmir',
       '#geohealthresearch-project-26;#PivotscienceActivity', '#ola;#rdv',
       '#irsju', '#hotosm-project-16875;#GeOSM;#PUC', '#adt',
       '#hotosm-project-17137;#bloomberg;#emea',
       '#hotosm-project-15229;#OSMIndia;#OSMNorthEastIndia;#GREd;#GREdFoundation;#AssamMapping23;#OMGuru;#APHub;#CCC2024;#tt_event',
       '#BANO;#Pifometre', '#amap', '#tomtom;#tt_mapfeedback',
       '#hotosm-project-14389;#MangochiDistrict;#msf;#missingmaps;#malawicholeraoutbreak',
       '#maproulette', '#OpenCampingMap', '#lgmaps', '#swiggy',
       '#PUC;#EST;#tt_event',
       '#hotosm-project-15188;#Ndjamena;#msf;#missingmaps;#Ndjamena2023;#Msft;#24VR',
       '#localknowledge;#grabosm',
       '#hotosm-project-16259;#osmTaiwan;#NLSCopendata;#rivertracing',
       '#MSFTOpenMaps',
       '#hotosm-project-17266;#UPMAPPERS;#WAFARI;#YouthMappers;#SouthAfrica;#ESADisasterResponse',
       '#maproulette;#tomtom', '#mapbox_linters', '#ola;#evf',
       '#hotosm-project-17320;#ESC2023;#WNAH;#HOT;#Map4CIV;#OSM20th;#osmGambia;#osmghana;#mapnigeria;#Map4Sn;#Map4NE;#humatarian-mappers',
       '#tomtom',
       '#hotosm-project-15008;#Tandjile;#msf;#missingmaps;#Tandjile2023',
       '#ola;#2xrdv', '#wbgeo', '#ola;#qcr',
       '#hotosm-project-17137;#bloomberg', '#کفش_کودک;#ninipa;#shoes',
       '#geoventurersFSU;#UnmappedSmallTownUSA', '#Pic4Review',
       '#grabosm',
       '#hotosm-project-16836;#ESAOMG2024;#GeoConnect;#ChinhoyiMunicipality;#OSMZimbabwe;#ChinhoyiOpenMapping;#Cutgeospatialsociety'],
      dtype=object)

### For the "unique" unique values (=1), what are they for each key ?

In [72]:
# list of tags with only 1 unique value
l_1 = list(df_uniques['tag'][df_uniques['unique_values'] == 1])
l_1[-5:] # last five

['answer',
 'warnings:close_nodes:vertices',
 'resolved:crossing_ways:highway-highway',
 'warnings:outdated_tags:noncanonical_brand',
 'resolved:crossing_ways:building-building']

In [73]:
df_tags['create'][~df_tags['create'].isna()]

352    1
838    1
Name: create, dtype: object

In [83]:
# show df for lines 352 and 838 : two changesets concerned by the same tag (NaN for all other changesets)
df_tags.iloc[[352,838]].T

,352,838
comment,Adding data with #MapComplete for theme #ghost...,Adding data with #MapComplete for theme #hotels
created_by,MapComplete 0.44.13,MapComplete 0.44.13
locale,de-DE,en
source,NaN,NaN
StreetComplete:quest_type,NaN,NaN
changesets_count,NaN,NaN
host,https://mapcomplete.org/ghostbikes.html,https://mapcomplete.org/hotels.html
ideditor:walkthrough_completed,NaN,NaN
ideditor:walkthrough_progress,NaN,NaN
ideditor:walkthrough_started,NaN,NaN
imagery_used,NaN,NaN
hashtags,NaN,NaN
resolved:almost_junction:highway-highway,NaN,NaN
data_used,NaN,NaN
resolved:help_request:fixme_tag,NaN,NaN
resolved:mismatched_geometry:point_as_vertex,NaN,NaN
resolved:outdated_tags:incomplete_tags,NaN,NaN
resolved:outdated_tags:noncanonical_brand,NaN,NaN
resolved:close_nodes:vertices,NaN,NaN
warnings:crossing_ways:highway-waterway,NaN,NaN
warnings:missing_tag:descriptive,NaN,NaN
bundle_id,NaN,NaN
warnings:crossing_ways:building-highway,NaN,NaN
warnings:disconnected_way:highway,NaN,NaN
closed:note,NaN,NaN
warnings:almost_junction:highway-highway,NaN,NaN
fixing_osm_roads,NaN,NaN
bot,NaN,NaN
cases_where_human_help_is_required,NaN,NaN
created_by_library,NaN,NaN
discussion_before_edits,NaN,NaN
mechanical,NaN,NaN
osm_wiki_documentation_page,NaN,NaN
review_requested,NaN,NaN
description,NaN,NaN
create,1,1
theme,ghostbikes,hotels
resolved:crossing_ways:highway-waterway,NaN,NaN
resolved:outdated_tags:deprecated_tags,NaN,NaN
info:features_merged,NaN,NaN
warnings:suspicious_name:generic_name,NaN,NaN
resolved:mismatched_geometry:line_as_vertex,NaN,NaN
resolved:mismatched_geometry:vertex_as_point,NaN,NaN
warnings:crossing_ways:highway-highway,NaN,NaN
resolved:disconnected_way:highway,NaN,NaN
warnings:mismatched_geometry:point_as_line,NaN,NaN
warnings:crossing_ways:building-building,NaN,NaN
resolved:crossing_ways:building-highway,NaN,NaN
resolved:crossing_ways:highway-railway,NaN,NaN
created_by:library,NaN,NaN
website,NaN,NaN
answer,NaN,NaN
warnings:close_nodes:vertices,NaN,NaN
resolved:crossing_ways:highway-highway,NaN,NaN
warnings:outdated_tags:noncanonical_brand,NaN,NaN
resolved:crossing_ways:building-building,NaN,NaN

In [75]:
df_tags['description'].value_counts().rename_axis('unique_values').reset_index(name='count')

                                       unique_values  count
0  https://wiki.openstreetmap.org/wiki/Automated_...      2

### DataFrame that sums up the occurrence of each unique uniques (unique values == 1)

In [84]:
df_tags[l_1].apply(pd.Series.value_counts).rename_axis('unique unique_values').T

unique unique_values,1,10,2,3820706,4,6,OSM Request 1.2.9,alias8,app.organicmaps,https://community.openstreetmap.org/t/mass-remove-gnis-created-and-similar-tags/107018,https://github.com/matkoniecz/osm_bot_abstraction_layer,https://matkoniecz.github.io/OSM-wikipedia-tag-validator-reports/,https://pic4review.pavie.info/#/mission/2732/review,https://wiki.openstreetmap.org/wiki/Automated_Edits/b-jazz,https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/remove_not_needed_GNIS_tags,yes
ideditor:walkthrough_completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
ideditor:walkthrough_started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0
resolved:almost_junction:highway-highway,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolved:help_request:fixme_tag,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolved:mismatched_geometry:point_as_vertex,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolved:close_nodes:vertices,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
warnings:missing_tag:descriptive,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bundle_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
warnings:crossing_ways:building-highway,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
closed:note,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
warnings:almost_junction:highway-highway,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fixing_osm_roads,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
cases_where_human_help_is_required,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
created_by_library,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
discussion_before_edits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
mechanical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
osm_wiki_documentation_page,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
review_requested,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
description,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN
create,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolved:outdated_tags:deprecated_tags,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
info:features_merged,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
warnings:suspicious_name:generic_name,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolved:mismatched_geometry:line_as_vertex,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolved:disconnected_way:highway,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
warnings:mismatched_geometry:point_as_line,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
warnings:crossing_ways:building-building,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolved:crossing_ways:highway-railway,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_by:library,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
website,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
answer,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
warnings:close_nodes:vertices,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolved:crossing_ways:highway-highway,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
warnings:outdated_tags:noncanonical_brand,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolved:crossing_ways:building-building,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get changeset counts via fetching .osm.gz files

In [1]:
def urlized_sequence_number(sequence_number):
    # returns url of the form https://planet.osm.org/replication/changesets/123/456/789.osm.gz
    sequence_number_adjusted = str(sequence_number).rjust(9, "0")
    return f"https://planet.osm.org/replication/changesets/{sequence_number_adjusted[0:3]}/{sequence_number_adjusted[3:6]}/{sequence_number_adjusted[6:9]}.osm.gz"

In [10]:
sequence_number = 6191420

url_sequence = urlized_sequence_number(sequence_number)
url_sequence

'https://planet.osm.org/replication/changesets/006/191/420.osm.gz'

In [11]:
import requests
import xml.etree.ElementTree as ET
import gzip
xml_sequence_request = requests.get(url_sequence, stream=True).raw.read()
xml_sequence = ET.fromstring(gzip.decompress(xml_sequence_request))
xml_sequence

In [12]:
# extract number of changesets in xml_sequence:

len(xml_sequence)

61

In [14]:
# checking all the unique names of elements in the xml tree

for elem in xml_sequence:
    if elem.tag != 'changeset':
        print(elem.tag)

In [15]:
# check for many sequences if there are elements in xml other than 'changeset'ET

sequence_numbers = range(6191400, 6191420)

tags_not_changeset = {}
for sequence_number in sequence_numbers:
    tags_not_changeset[sequence_number] = []
    url_sequence = urlized_sequence_number(sequence_number)
    xml_sequence_request = requests.get(url_sequence, stream=True).raw.read()
    xml_sequence = ET.fromstring(gzip.decompress(xml_sequence_request))
    for elem in xml_sequence:
        if elem.tag != 'changeset':
            print(elem.tag)
            tags_not_changeset[sequence_number].append(elem.tag)

print(tags_not_changeset)

{6191400: [], 6191401: [], 6191402: [], 6191403: [], 6191404: [], 6191405: [], 6191406: [], 6191407: [], 6191408: [], 6191409: [], 6191410: [], 6191411: [], 6191412: [], 6191413: [], 6191414: [], 6191415: [], 6191416: [], 6191417: [], 6191418: [], 6191419: []}

In [16]:
def get_last_sequence():
    import yaml, requests
    """Fetches the latest sequence from the state.yaml file."""
    response = requests.get("https://planet.osm.org/replication/changesets/state.yaml", stream=True)
    last_sequence = int(yaml.load(response.raw.read(), Loader=yaml.FullLoader)["sequence"])
    return last_sequence

In [31]:
def get_changeset_count(sequence):
    """ Fetches changesets using urlized sequence number and extract the length of the xml tree <=> nb of changesets """
    url_sequence = urlized_sequence_number(sequence)
    xml_sequence_request = requests.get(url_sequence, stream=True).raw.read()
    xml_sequence = ET.fromstring(gzip.decompress(xml_sequence_request))
    return len(xml_sequence)

In [32]:
last_fetched_sequence = None

def update_changeset_view():
    global last_fetched_sequence
    new_sequence = get_last_sequence()
    # Check if the new sequence is different from the previous one
    if new_sequence != last_fetched_sequence:
        changeset_count = get_changeset_count(new_sequence)
        print(changeset_count)
        last_fetched_sequence = new_sequence  # Update the last fetched sequence
        return {"sequence": new_sequence, "changeset_count": changeset_count}

    # If there's no new sequence, return an empty response to avoid updating
    return {"sequence": last_fetched_sequence, "changeset_count": None}

update_changeset_view()

36

{'sequence': 6191463, 'changeset_count': 36}

In [23]:
type(get_changeset_count(6191457))

int

In [33]:
def get_last_sequence_test():
    import yaml, requests
    """Fetches the latest sequence from the state.yaml file."""
    response = requests.get("https://planet.osm.org/replication/changesets/state.yaml", stream=True)
    last_sequence = int(yaml.load(response.raw.read(), Loader=yaml.FullLoader)["sequence"])
    last_run = yaml.load(response.raw.read(), Loader=yaml.FullLoader)["last_run"]
    return last_sequence, last_run

In [43]:
def get_sequence_timestamp(sequence):
    # fetch https://planet.osm.org/replication/changesets/123/456/789
    sequence_number_adjusted = str(sequence_number).rjust(9, "0")
    url = f"https://planet.osm.org/replication/changesets/{sequence_number_adjusted[0:3]}/{sequence_number_adjusted[3:6]}/{sequence_number_adjusted[6:9]}"

('https://planet.osm.org/replication/changesets/006/191/463.osm.gz',
 'https://planet.osm.org/replication/changesets/006/191/463.state.text')

In [52]:
import requests
from bs4 import BeautifulSoup

def extract_timestamps(url, number_range):
    # Fetch the HTML content from the URL
    response = requests.get(url)
    html_content = response.text

    # Parse the HTML content using BeautifulSoup
    soup = BeautifulSoup(html_content, 'html.parser')

    # Initialize a dictionary to store the timestamps
    timestamps = {}

    # Loop through the anchor tags
    for a_tag in soup.find_all('a', href=True):
        href = a_tag['href']
        # Check if the href contains a number in the specified range followed by ".state.txt"
        if href.endswith('.state.txt'):
            number = int(href.split('.')[0])
            if number in number_range:
                # Extract the timestamp from the next sibling text
                timestamp = a_tag.find_next_sibling(text=True).strip().split()[:2]
                timestamps[number] = timestamp

    return timestamps

# Example usage
url = 'https://planet.osm.org/replication/changesets/006/191/'  # Replace with the actual URL
number_range = range(416, 421)  # Specify the range of numbers
timestamps = extract_timestamps(url, number_range)

# Print the extracted timestamps
for number, timestamp in timestamps.items():
    print(f"Number: {number}, Timestamp: {timestamp}")

Number: 420, Timestamp: ['2024-09-22', '08:23']
Number: 419, Timestamp: ['2024-09-22', '08:22']
Number: 418, Timestamp: ['2024-09-22', '08:21']
Number: 417, Timestamp: ['2024-09-22', '08:20']
Number: 416, Timestamp: ['2024-09-22', '08:19']

/var/folders/n_/b2v5x65d6fvgkr8svqh31qww0000gn/T/ipykernel_55875/539943160.py:23: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  timestamp = a_tag.find_next_sibling(text=True).strip().split()[:2]

In [51]:
timestamps[420].split()[:2]

['2024-09-22', '08:23']

In [65]:
sequence = 6191497
sequence_last_3 = int(str(sequence)[-3:])
print(sequence_last_3)

497

In [66]:
sequence_adjusted = str(sequence_number).rjust(9, "0")
url = f"https://planet.osm.org/replication/changesets/{sequence_adjusted[0:3]}/{sequence_adjusted[3:6]}/"
response = requests.get(url)
html_content = response.text
soup = BeautifulSoup(html_content, 'html.parser')

In [73]:
soup.find_all('a', href=True)

[<a href="?C=N;O=A">Name</a>,
 <a href="?C=M;O=A">Last modified</a>,
 <a href="?C=S;O=A">Size</a>,
 <a href="?C=D;O=A">Description</a>,
 <a href="/replication/changesets/006/">Parent Directory</a>,
 <a href="747.state.txt">747.state.txt</a>,
 <a href="747.osm.gz">747.osm.gz</a>,
 <a href="746.state.txt">746.state.txt</a>,
 <a href="746.osm.gz">746.osm.gz</a>,
 <a href="745.state.txt">745.state.txt</a>,
 <a href="745.osm.gz">745.osm.gz</a>,
 <a href="744.state.txt">744.state.txt</a>,
 <a href="744.osm.gz">744.osm.gz</a>,
 <a href="743.state.txt">743.state.txt</a>,
 <a href="743.osm.gz">743.osm.gz</a>,
 <a href="742.state.txt">742.state.txt</a>,
 <a href="742.osm.gz">742.osm.gz</a>,
 <a href="741.state.txt">741.state.txt</a>,
 <a href="741.osm.gz">741.osm.gz</a>,
 <a href="740.state.txt">740.state.txt</a>,
 <a href="740.osm.gz">740.osm.gz</a>,
 <a href="739.state.txt">739.state.txt</a>,
 <a href="739.osm.gz">739.osm.gz</a>,
 <a href="738.state.txt">738.state.txt</a>,
 <a href="738.osm.gz">738.osm.gz</a>,
 <a href="737.state.txt">737.state.txt</a>,
 <a href="737.osm.gz">737.osm.gz</a>,
 <a href="736.state.txt">736.state.txt</a>,
 <a href="736.osm.gz">736.osm.gz</a>,
 <a href="735.state.txt">735.state.txt</a>,
 <a href="735.osm.gz">735.osm.gz</a>,
 <a href="734.state.txt">734.state.txt</a>,
 <a href="734.osm.gz">734.osm.gz</a>,
 <a href="733.state.txt">733.state.txt</a>,
 <a href="733.osm.gz">733.osm.gz</a>,
 <a href="732.state.txt">732.state.txt</a>,
 <a href="732.osm.gz">732.osm.gz</a>,
 <a href="731.state.txt">731.state.txt</a>,
 <a href="731.osm.gz">731.osm.gz</a>,
 <a href="730.state.txt">730.state.txt</a>,
 <a href="730.osm.gz">730.osm.gz</a>,
 <a href="729.state.txt">729.state.txt</a>,
 <a href="729.osm.gz">729.osm.gz</a>,
 <a href="728.state.txt">728.state.txt</a>,
 <a href="728.osm.gz">728.osm.gz</a>,
 <a href="727.state.txt">727.state.txt</a>,
 <a href="727.osm.gz">727.osm.gz</a>,
 <a href="726.state.txt">726.state.txt</a>,
 <a href="726.osm.gz">726.osm.gz</a>,
 <a href="725.state.txt">725.state.txt</a>,
 <a href="725.osm.gz">725.osm.gz</a>,
 <a href="724.state.txt">724.state.txt</a>,
 <a href="724.osm.gz">724.osm.gz</a>,
 <a href="723.state.txt">723.state.txt</a>,
 <a href="723.osm.gz">723.osm.gz</a>,
 <a href="722.state.txt">722.state.txt</a>,
 <a href="722.osm.gz">722.osm.gz</a>,
 <a href="721.state.txt">721.state.txt</a>,
 <a href="721.osm.gz">721.osm.gz</a>,
 <a href="720.state.txt">720.state.txt</a>,
 <a href="720.osm.gz">720.osm.gz</a>,
 <a href="719.state.txt">719.state.txt</a>,
 <a href="719.osm.gz">719.osm.gz</a>,
 <a href="718.state.txt">718.state.txt</a>,
 <a href="718.osm.gz">718.osm.gz</a>,
 <a href="717.state.txt">717.state.txt</a>,
 <a href="717.osm.gz">717.osm.gz</a>,
 <a href="716.state.txt">716.state.txt</a>,
 <a href="716.osm.gz">716.osm.gz</a>,
 <a href="715.state.txt">715.state.txt</a>,
 <a href="715.osm.gz">715.osm.gz</a>,
 <a href="714.state.txt">714.state.txt</a>,
 <a href="714.osm.gz">714.osm.gz</a>,
 <a href="713.state.txt">713.state.txt</a>,
 <a href="713.osm.gz">713.osm.gz</a>,
 <a href="712.state.txt">712.state.txt</a>,
 <a href="712.osm.gz">712.osm.gz</a>,
 <a href="711.state.txt">711.state.txt</a>,
 <a href="711.osm.gz">711.osm.gz</a>,
 <a href="710.state.txt">710.state.txt</a>,
 <a href="710.osm.gz">710.osm.gz</a>,
 <a href="709.state.txt">709.state.txt</a>,
 <a href="709.osm.gz">709.osm.gz</a>,
 <a href="708.state.txt">708.state.txt</a>,
 <a href="708.osm.gz">708.osm.gz</a>,
 <a href="707.state.txt">707.state.txt</a>,
 <a href="707.osm.gz">707.osm.gz</a>,
 <a href="706.state.txt">706.state.txt</a>,
 <a href="706.osm.gz">706.osm.gz</a>,
 <a href="705.state.txt">705.state.txt</a>,
 <a href="705.osm.gz">705.osm.gz</a>,
 <a href="704.state.txt">704.state.txt</a>,
 <a href="704.osm.gz">704.osm.gz</a>,
 <a href="703.state.txt">703.state.txt</a>,
 <a href="703.osm.gz">703.osm.gz</a>,
 <a href="702.state.txt">702.state.txt</a>,
 <a href="702.osm.gz">702.osm.gz</a>,
 <a href="701.state.txt">701.state.txt</a>,
 <a href="701.osm.gz">701.osm.gz</a>,
 <a href="700.state.txt">700.state.txt</a>,
 <a href="700.osm.gz">700.osm.gz</a>,
 <a href="699.state.txt">699.state.txt</a>,
 <a href="699.osm.gz">699.osm.gz</a>,
 <a href="698.state.txt">698.state.txt</a>,
 <a href="698.osm.gz">698.osm.gz</a>,
 <a href="697.state.txt">697.state.txt</a>,
 <a href="697.osm.gz">697.osm.gz</a>,
 <a href="696.state.txt">696.state.txt</a>,
 <a href="696.osm.gz">696.osm.gz</a>,
 <a href="695.state.txt">695.state.txt</a>,
 <a href="695.osm.gz">695.osm.gz</a>,
 <a href="694.state.txt">694.state.txt</a>,
 <a href="694.osm.gz">694.osm.gz</a>,
 <a href="693.state.txt">693.state.txt</a>,
 <a href="693.osm.gz">693.osm.gz</a>,
 <a href="692.state.txt">692.state.txt</a>,
 <a href="692.osm.gz">692.osm.gz</a>,
 <a href="691.state.txt">691.state.txt</a>,
 <a href="691.osm.gz">691.osm.gz</a>,
 <a href="690.state.txt">690.state.txt</a>,
 <a href="690.osm.gz">690.osm.gz</a>,
 <a href="689.state.txt">689.state.txt</a>,
 <a href="689.osm.gz">689.osm.gz</a>,
 <a href="688.state.txt">688.state.txt</a>,
 <a href="688.osm.gz">688.osm.gz</a>,
 <a href="687.state.txt">687.state.txt</a>,
 <a href="687.osm.gz">687.osm.gz</a>,
 <a href="686.state.txt">686.state.txt</a>,
 <a href="686.osm.gz">686.osm.gz</a>,
 <a href="685.state.txt">685.state.txt</a>,
 <a href="685.osm.gz">685.osm.gz</a>,
 <a href="684.state.txt">684.state.txt</a>,
 <a href="684.osm.gz">684.osm.gz</a>,
 <a href="683.state.txt">683.state.txt</a>,
 <a href="683.osm.gz">683.osm.gz</a>,
 <a href="682.state.txt">682.state.txt</a>,
 <a href="682.osm.gz">682.osm.gz</a>,
 <a href="681.state.txt">681.state.txt</a>,
 <a href="681.osm.gz">681.osm.gz</a>,
 <a href="680.state.txt">680.state.txt</a>,
 <a href="680.osm.gz">680.osm.gz</a>,
 <a href="679.state.txt">679.state.txt</a>,
 <a href="679.osm.gz">679.osm.gz</a>,
 <a href="678.state.txt">678.state.txt</a>,
 <a href="678.osm.gz">678.osm.gz</a>,
 <a href="677.state.txt">677.state.txt</a>,
 <a href="677.osm.gz">677.osm.gz</a>,
 <a href="676.state.txt">676.state.txt</a>,
 <a href="676.osm.gz">676.osm.gz</a>,
 <a href="675.state.txt">675.state.txt</a>,
 <a href="675.osm.gz">675.osm.gz</a>,
 <a href="674.state.txt">674.state.txt</a>,
 <a href="674.osm.gz">674.osm.gz</a>,
 <a href="673.state.txt">673.state.txt</a>,
 <a href="673.osm.gz">673.osm.gz</a>,
 <a href="672.state.txt">672.state.txt</a>,
 <a href="672.osm.gz">672.osm.gz</a>,
 <a href="671.state.txt">671.state.txt</a>,
 <a href="671.osm.gz">671.osm.gz</a>,
 <a href="670.state.txt">670.state.txt</a>,
 <a href="670.osm.gz">670.osm.gz</a>,
 <a href="669.state.txt">669.state.txt</a>,
 <a href="669.osm.gz">669.osm.gz</a>,
 <a href="668.state.txt">668.state.txt</a>,
 <a href="668.osm.gz">668.osm.gz</a>,
 <a href="667.state.txt">667.state.txt</a>,
 <a href="667.osm.gz">667.osm.gz</a>,
 <a href="666.state.txt">666.state.txt</a>,
 <a href="666.osm.gz">666.osm.gz</a>,
 <a href="665.state.txt">665.state.txt</a>,
 <a href="665.osm.gz">665.osm.gz</a>,
 <a href="664.state.txt">664.state.txt</a>,
 <a href="664.osm.gz">664.osm.gz</a>,
 <a href="663.state.txt">663.state.txt</a>,
 <a href="663.osm.gz">663.osm.gz</a>,
 <a href="662.state.txt">662.state.txt</a>,
 <a href="662.osm.gz">662.osm.gz</a>,
 <a href="661.state.txt">661.state.txt</a>,
 <a href="661.osm.gz">661.osm.gz</a>,
 <a href="660.state.txt">660.state.txt</a>,
 <a href="660.osm.gz">660.osm.gz</a>,
 <a href="659.state.txt">659.state.txt</a>,
 <a href="659.osm.gz">659.osm.gz</a>,
 <a href="658.state.txt">658.state.txt</a>,
 <a href="658.osm.gz">658.osm.gz</a>,
 <a href="657.state.txt">657.state.txt</a>,
 <a href="657.osm.gz">657.osm.gz</a>,
 <a href="656.state.txt">656.state.txt</a>,
 <a href="656.osm.gz">656.osm.gz</a>,
 <a href="655.state.txt">655.state.txt</a>,
 <a href="655.osm.gz">655.osm.gz</a>,
 <a href="654.state.txt">654.state.txt</a>,
 <a href="654.osm.gz">654.osm.gz</a>,
 <a href="653.state.txt">653.state.txt</a>,
 <a href="653.osm.gz">653.osm.gz</a>,
 <a href="652.state.txt">652.state.txt</a>,
 <a href="652.osm.gz">652.osm.gz</a>,
 <a href="651.state.txt">651.state.txt</a>,
 <a href="651.osm.gz">651.osm.gz</a>,
 <a href="650.state.txt">650.state.txt</a>,
 <a href="650.osm.gz">650.osm.gz</a>,
 <a href="649.state.txt">649.state.txt</a>,
 <a href="649.osm.gz">649.osm.gz</a>,
 <a href="648.state.txt">648.state.txt</a>,
 <a href="648.osm.gz">648.osm.gz</a>,
 <a href="647.state.txt">647.state.txt</a>,
 <a href="647.osm.gz">647.osm.gz</a>,
 <a href="646.state.txt">646.state.txt</a>,
 <a href="646.osm.gz">646.osm.gz</a>,
 <a href="645.state.txt">645.state.txt</a>,
 <a href="645.osm.gz">645.osm.gz</a>,
 <a href="644.state.txt">644.state.txt</a>,
 <a href="644.osm.gz">644.osm.gz</a>,
 <a href="643.state.txt">643.state.txt</a>,
 <a href="643.osm.gz">643.osm.gz</a>,
 <a href="642.state.txt">642.state.txt</a>,
 <a href="642.osm.gz">642.osm.gz</a>,
 <a href="641.state.txt">641.state.txt</a>,
 <a href="641.osm.gz">641.osm.gz</a>,
 <a href="640.state.txt">640.state.txt</a>,
 <a href="640.osm.gz">640.osm.gz</a>,
 <a href="639.state.txt">639.state.txt</a>,
 <a href="639.osm.gz">639.osm.gz</a>,
 <a href="638.state.txt">638.state.txt</a>,
 <a href="638.osm.gz">638.osm.gz</a>,
 <a href="637.state.txt">637.state.txt</a>,
 <a href="637.osm.gz">637.osm.gz</a>,
 <a href="636.state.txt">636.state.txt</a>,
 <a href="636.osm.gz">636.osm.gz</a>,
 <a href="635.state.txt">635.state.txt</a>,
 <a href="635.osm.gz">635.osm.gz</a>,
 <a href="634.state.txt">634.state.txt</a>,
 <a href="634.osm.gz">634.osm.gz</a>,
 <a href="633.state.txt">633.state.txt</a>,
 <a href="633.osm.gz">633.osm.gz</a>,
 <a href="632.state.txt">632.state.txt</a>,
 <a href="632.osm.gz">632.osm.gz</a>,
 <a href="631.state.txt">631.state.txt</a>,
 <a href="631.osm.gz">631.osm.gz</a>,
 <a href="630.state.txt">630.state.txt</a>,
 <a href="630.osm.gz">630.osm.gz</a>,
 <a href="629.state.txt">629.state.txt</a>,
 <a href="629.osm.gz">629.osm.gz</a>,
 <a href="628.state.txt">628.state.txt</a>,
 <a href="628.osm.gz">628.osm.gz</a>,
 <a href="627.state.txt">627.state.txt</a>,
 <a href="627.osm.gz">627.osm.gz</a>,
 <a href="626.state.txt">626.state.txt</a>,
 <a href="626.osm.gz">626.osm.gz</a>,
 <a href="625.state.txt">625.state.txt</a>,
 <a href="625.osm.gz">625.osm.gz</a>,
 <a href="624.state.txt">624.state.txt</a>,
 <a href="624.osm.gz">624.osm.gz</a>,
 <a href="623.state.txt">623.state.txt</a>,
 <a href="623.osm.gz">623.osm.gz</a>,
 <a href="622.state.txt">622.state.txt</a>,
 <a href="622.osm.gz">622.osm.gz</a>,
 <a href="621.state.txt">621.state.txt</a>,
 <a href="621.osm.gz">621.osm.gz</a>,
 <a href="620.state.txt">620.state.txt</a>,
 <a href="620.osm.gz">620.osm.gz</a>,
 <a href="619.state.txt">619.state.txt</a>,
 <a href="619.osm.gz">619.osm.gz</a>,
 <a href="618.state.txt">618.state.txt</a>,
 <a href="618.osm.gz">618.osm.gz</a>,
 <a href="617.state.txt">617.state.txt</a>,
 <a href="617.osm.gz">617.osm.gz</a>,
 <a href="616.state.txt">616.state.txt</a>,
 <a href="616.osm.gz">616.osm.gz</a>,
 <a href="615.state.txt">615.state.txt</a>,
 <a href="615.osm.gz">615.osm.gz</a>,
 <a href="614.state.txt">614.state.txt</a>,
 <a href="614.osm.gz">614.osm.gz</a>,
 <a href="613.state.txt">613.state.txt</a>,
 <a href="613.osm.gz">613.osm.gz</a>,
 <a href="612.state.txt">612.state.txt</a>,
 <a href="612.osm.gz">612.osm.gz</a>,
 <a href="611.state.txt">611.state.txt</a>,
 <a href="611.osm.gz">611.osm.gz</a>,
 <a href="610.state.txt">610.state.txt</a>,
 <a href="610.osm.gz">610.osm.gz</a>,
 <a href="609.state.txt">609.state.txt</a>,
 <a href="609.osm.gz">609.osm.gz</a>,
 <a href="608.state.txt">608.state.txt</a>,
 <a href="608.osm.gz">608.osm.gz</a>,
 <a href="607.state.txt">607.state.txt</a>,
 <a href="607.osm.gz">607.osm.gz</a>,
 <a href="606.state.txt">606.state.txt</a>,
 <a href="606.osm.gz">606.osm.gz</a>,
 <a href="605.state.txt">605.state.txt</a>,
 <a href="605.osm.gz">605.osm.gz</a>,
 <a href="604.state.txt">604.state.txt</a>,
 <a href="604.osm.gz">604.osm.gz</a>,
 <a href="603.state.txt">603.state.txt</a>,
 <a href="603.osm.gz">603.osm.gz</a>,
 <a href="602.state.txt">602.state.txt</a>,
 <a href="602.osm.gz">602.osm.gz</a>,
 <a href="601.state.txt">601.state.txt</a>,
 <a href="601.osm.gz">601.osm.gz</a>,
 <a href="600.state.txt">600.state.txt</a>,
 <a href="600.osm.gz">600.osm.gz</a>,
 <a href="599.state.txt">599.state.txt</a>,
 <a href="599.osm.gz">599.osm.gz</a>,
 <a href="598.state.txt">598.state.txt</a>,
 <a href="598.osm.gz">598.osm.gz</a>,
 <a href="597.state.txt">597.state.txt</a>,
 <a href="597.osm.gz">597.osm.gz</a>,
 <a href="596.state.txt">596.state.txt</a>,
 <a href="596.osm.gz">596.osm.gz</a>,
 <a href="595.state.txt">595.state.txt</a>,
 <a href="595.osm.gz">595.osm.gz</a>,
 <a href="594.state.txt">594.state.txt</a>,
 <a href="594.osm.gz">594.osm.gz</a>,
 <a href="593.state.txt">593.state.txt</a>,
 <a href="593.osm.gz">593.osm.gz</a>,
 <a href="592.state.txt">592.state.txt</a>,
 <a href="592.osm.gz">592.osm.gz</a>,
 <a href="591.state.txt">591.state.txt</a>,
 <a href="591.osm.gz">591.osm.gz</a>,
 <a href="590.state.txt">590.state.txt</a>,
 <a href="590.osm.gz">590.osm.gz</a>,
 <a href="589.state.txt">589.state.txt</a>,
 <a href="589.osm.gz">589.osm.gz</a>,
 <a href="588.state.txt">588.state.txt</a>,
 <a href="588.osm.gz">588.osm.gz</a>,
 <a href="587.state.txt">587.state.txt</a>,
 <a href="587.osm.gz">587.osm.gz</a>,
 <a href="586.state.txt">586.state.txt</a>,
 <a href="586.osm.gz">586.osm.gz</a>,
 <a href="585.state.txt">585.state.txt</a>,
 <a href="585.osm.gz">585.osm.gz</a>,
 <a href="584.state.txt">584.state.txt</a>,
 <a href="584.osm.gz">584.osm.gz</a>,
 <a href="583.state.txt">583.state.txt</a>,
 <a href="583.osm.gz">583.osm.gz</a>,
 <a href="582.state.txt">582.state.txt</a>,
 <a href="582.osm.gz">582.osm.gz</a>,
 <a href="581.state.txt">581.state.txt</a>,
 <a href="581.osm.gz">581.osm.gz</a>,
 <a href="580.state.txt">580.state.txt</a>,
 <a href="580.osm.gz">580.osm.gz</a>,
 <a href="579.state.txt">579.state.txt</a>,
 <a href="579.osm.gz">579.osm.gz</a>,
 <a href="578.state.txt">578.state.txt</a>,
 <a href="578.osm.gz">578.osm.gz</a>,
 <a href="577.state.txt">577.state.txt</a>,
 <a href="577.osm.gz">577.osm.gz</a>,
 <a href="576.state.txt">576.state.txt</a>,
 <a href="576.osm.gz">576.osm.gz</a>,
 <a href="575.state.txt">575.state.txt</a>,
 <a href="575.osm.gz">575.osm.gz</a>,
 <a href="574.state.txt">574.state.txt</a>,
 <a href="574.osm.gz">574.osm.gz</a>,
 <a href="573.state.txt">573.state.txt</a>,
 <a href="573.osm.gz">573.osm.gz</a>,
 <a href="572.state.txt">572.state.txt</a>,
 <a href="572.osm.gz">572.osm.gz</a>,
 <a href="571.state.txt">571.state.txt</a>,
 <a href="571.osm.gz">571.osm.gz</a>,
 <a href="570.state.txt">570.state.txt</a>,
 <a href="570.osm.gz">570.osm.gz</a>,
 <a href="569.state.txt">569.state.txt</a>,
 <a href="569.osm.gz">569.osm.gz</a>,
 <a href="568.state.txt">568.state.txt</a>,
 <a href="568.osm.gz">568.osm.gz</a>,
 <a href="567.state.txt">567.state.txt</a>,
 <a href="567.osm.gz">567.osm.gz</a>,
 <a href="566.state.txt">566.state.txt</a>,
 <a href="566.osm.gz">566.osm.gz</a>,
 <a href="565.state.txt">565.state.txt</a>,
 <a href="565.osm.gz">565.osm.gz</a>,
 <a href="564.state.txt">564.state.txt</a>,
 <a href="564.osm.gz">564.osm.gz</a>,
 <a href="563.state.txt">563.state.txt</a>,
 <a href="563.osm.gz">563.osm.gz</a>,
 <a href="562.state.txt">562.state.txt</a>,
 <a href="562.osm.gz">562.osm.gz</a>,
 <a href="561.state.txt">561.state.txt</a>,
 <a href="561.osm.gz">561.osm.gz</a>,
 <a href="560.state.txt">560.state.txt</a>,
 <a href="560.osm.gz">560.osm.gz</a>,
 <a href="559.state.txt">559.state.txt</a>,
 <a href="559.osm.gz">559.osm.gz</a>,
 <a href="558.state.txt">558.state.txt</a>,
 <a href="558.osm.gz">558.osm.gz</a>,
 <a href="557.state.txt">557.state.txt</a>,
 <a href="557.osm.gz">557.osm.gz</a>,
 <a href="556.state.txt">556.state.txt</a>,
 <a href="556.osm.gz">556.osm.gz</a>,
 <a href="555.state.txt">555.state.txt</a>,
 <a href="555.osm.gz">555.osm.gz</a>,
 <a href="554.state.txt">554.state.txt</a>,
 <a href="554.osm.gz">554.osm.gz</a>,
 <a href="553.state.txt">553.state.txt</a>,
 <a href="553.osm.gz">553.osm.gz</a>,
 <a href="552.state.txt">552.state.txt</a>,
 <a href="552.osm.gz">552.osm.gz</a>,
 <a href="551.state.txt">551.state.txt</a>,
 <a href="551.osm.gz">551.osm.gz</a>,
 <a href="550.state.txt">550.state.txt</a>,
 <a href="550.osm.gz">550.osm.gz</a>,
 <a href="549.state.txt">549.state.txt</a>,
 <a href="549.osm.gz">549.osm.gz</a>,
 <a href="548.state.txt">548.state.txt</a>,
 <a href="548.osm.gz">548.osm.gz</a>,
 <a href="547.state.txt">547.state.txt</a>,
 <a href="547.osm.gz">547.osm.gz</a>,
 <a href="546.state.txt">546.state.txt</a>,
 <a href="546.osm.gz">546.osm.gz</a>,
 <a href="545.state.txt">545.state.txt</a>,
 <a href="545.osm.gz">545.osm.gz</a>,
 <a href="544.state.txt">544.state.txt</a>,
 <a href="544.osm.gz">544.osm.gz</a>,
 <a href="543.state.txt">543.state.txt</a>,
 <a href="543.osm.gz">543.osm.gz</a>,
 <a href="542.state.txt">542.state.txt</a>,
 <a href="542.osm.gz">542.osm.gz</a>,
 <a href="541.state.txt">541.state.txt</a>,
 <a href="541.osm.gz">541.osm.gz</a>,
 <a href="540.state.txt">540.state.txt</a>,
 <a href="540.osm.gz">540.osm.gz</a>,
 <a href="539.state.txt">539.state.txt</a>,
 <a href="539.osm.gz">539.osm.gz</a>,
 <a href="538.state.txt">538.state.txt</a>,
 <a href="538.osm.gz">538.osm.gz</a>,
 <a href="537.state.txt">537.state.txt</a>,
 <a href="537.osm.gz">537.osm.gz</a>,
 <a href="536.state.txt">536.state.txt</a>,
 <a href="536.osm.gz">536.osm.gz</a>,
 <a href="535.state.txt">535.state.txt</a>,
 <a href="535.osm.gz">535.osm.gz</a>,
 <a href="534.state.txt">534.state.txt</a>,
 <a href="534.osm.gz">534.osm.gz</a>,
 <a href="533.state.txt">533.state.txt</a>,
 <a href="533.osm.gz">533.osm.gz</a>,
 <a href="532.state.txt">532.state.txt</a>,
 <a href="532.osm.gz">532.osm.gz</a>,
 <a href="531.state.txt">531.state.txt</a>,
 <a href="531.osm.gz">531.osm.gz</a>,
 <a href="530.state.txt">530.state.txt</a>,
 <a href="530.osm.gz">530.osm.gz</a>,
 <a href="529.state.txt">529.state.txt</a>,
 <a href="529.osm.gz">529.osm.gz</a>,
 <a href="528.state.txt">528.state.txt</a>,
 <a href="528.osm.gz">528.osm.gz</a>,
 <a href="527.state.txt">527.state.txt</a>,
 <a href="527.osm.gz">527.osm.gz</a>,
 <a href="526.state.txt">526.state.txt</a>,
 <a href="526.osm.gz">526.osm.gz</a>,
 <a href="525.state.txt">525.state.txt</a>,
 <a href="525.osm.gz">525.osm.gz</a>,
 <a href="524.state.txt">524.state.txt</a>,
 <a href="524.osm.gz">524.osm.gz</a>,
 <a href="523.state.txt">523.state.txt</a>,
 <a href="523.osm.gz">523.osm.gz</a>,
 <a href="522.state.txt">522.state.txt</a>,
 <a href="522.osm.gz">522.osm.gz</a>,
 <a href="521.state.txt">521.state.txt</a>,
 <a href="521.osm.gz">521.osm.gz</a>,
 <a href="520.state.txt">520.state.txt</a>,
 <a href="520.osm.gz">520.osm.gz</a>,
 <a href="519.state.txt">519.state.txt</a>,
 <a href="519.osm.gz">519.osm.gz</a>,
 <a href="518.state.txt">518.state.txt</a>,
 <a href="518.osm.gz">518.osm.gz</a>,
 <a href="517.state.txt">517.state.txt</a>,
 <a href="517.osm.gz">517.osm.gz</a>,
 <a href="516.state.txt">516.state.txt</a>,
 <a href="516.osm.gz">516.osm.gz</a>,
 <a href="515.state.txt">515.state.txt</a>,
 <a href="515.osm.gz">515.osm.gz</a>,
 <a href="514.state.txt">514.state.txt</a>,
 <a href="514.osm.gz">514.osm.gz</a>,
 <a href="513.state.txt">513.state.txt</a>,
 <a href="513.osm.gz">513.osm.gz</a>,
 <a href="512.state.txt">512.state.txt</a>,
 <a href="512.osm.gz">512.osm.gz</a>,
 <a href="511.state.txt">511.state.txt</a>,
 <a href="511.osm.gz">511.osm.gz</a>,
 <a href="510.state.txt">510.state.txt</a>,
 <a href="510.osm.gz">510.osm.gz</a>,
 <a href="509.state.txt">509.state.txt</a>,
 <a href="509.osm.gz">509.osm.gz</a>,
 <a href="508.state.txt">508.state.txt</a>,
 <a href="508.osm.gz">508.osm.gz</a>,
 <a href="507.state.txt">507.state.txt</a>,
 <a href="507.osm.gz">507.osm.gz</a>,

In [74]:
a_list = []
for a_tag in soup.find_all('a', href=True):
    href = a_tag['href']
    if href.endswith('.state.txt'):
        number = int(href.split('.')[0])
        sequence_last_3 = int(str(sequence)[-3:])
        if number in range(sequence_last_3 - 10, sequence_last_3):
            a_list.append(a_tag)

In [81]:
a_list[0].find_next_sibling(string=True)

'                2024-09-22 09:41   69   \n'

In [96]:
def scrape_timestamps(sequence, n_range=10):
    """Scrapes the timestamps of the last n_range changesets"""
    sequence_adjusted = str(sequence_number).rjust(9, "0")
    url = f"https://planet.osm.org/replication/changesets/{sequence_adjusted[0:3]}/{sequence_adjusted[3:6]}/"
    response = requests.get(url)
    html_content = response.text
    soup = BeautifulSoup(html_content, 'html.parser')
    timestamps = {}

    for a_tag in soup.find_all('a', href=True):
        href = a_tag['href']
        if href.endswith('.state.txt'):
            number = int(href.split('.')[0])
            sequence_last_3 = int(str(sequence)[-3:])
            if number in range(sequence_last_3 - n_range + 1, sequence_last_3 + 1):
                timestamp = a_tag.find_next_sibling(string=True).strip().split()[:2]
                timestamps[number] = timestamp
    return timestamps

timestamps = scrape_timestamps(6191770)

In [97]:
sequence_number = 6191770
print(f'timestamps dict : {timestamps}, length : {len(timestamps)}')
print(int(str(sequence_number)[-3:]), type(int(str(sequence_number)[-3:])))
timestamps[int(str(sequence_number)[-3:])][1]

timestamps dict : {770: ['2024-09-22', '14:24'], 769: ['2024-09-22', '14:23'], 768: ['2024-09-22', '14:21'], 767: ['2024-09-22', '14:20'], 766: ['2024-09-22', '14:19'], 765: ['2024-09-22', '14:18'], 764: ['2024-09-22', '14:17'], 763: ['2024-09-22', '14:16'], 762: ['2024-09-22', '14:15'], 761: ['2024-09-22', '14:14']}, length : 10
770 <class 'int'>

'14:24'